# Generated by Django 5.0 on 2025-02-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityquestion',
            old_name='total',
            new_name='text',
        ),
    ]
